apiVersion: cloudamqp.com.cloudamqp.com/v1alpha1
kind: LavinMQ
metadata:
  labels:
    app.kubernetes.io/name: operator-sdk
    app.kubernetes.io/managed-by: kustomize
    app: lavinmq-sample
  name: lavinmq-sample
spec:
  image: cloudamqp/lavinmq:2.2.0
  replicas: 1
  etcdEndpoints:
    - etcd-cluster-0.etcd-cluster.default.svc.cluster.local:2379
    - etcd-cluster-1.etcd-cluster.default.svc.cluster.local:2379
    - etcd-cluster-2.etcd-cluster.default.svc.cluster.local:2379
  tlsSecret:
    name: lavinmq-tls
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
  config:
    main:
      consumer_timeout: 20000
      default_consumer_prefetch: 100
    mgmt:
      port: 8080
    amqp:
      channel_max: 100
    mqtt:
      max_inflight_messages: 100
      port: -1
    clustering:
      max_unsynced_actions: 8192
