apiVersion: cloudamqp.com.cloudamqp.com/v1alpha1
kind: LavinMQ
metadata:
  labels:
    app.kubernetes.io/name: operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: lavinmq-sample
spec:
  replicas: 1
  ports:
    - containerPort: 15672
      name: http
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
